import CallsData from '@/components/calls/CallsData';
import Header from '@/components/header/Header';

import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-JS Task</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main>
        <Header />
        <CallsData />
      </main>
    </>
  );
}
